# Generated by Django 5.0.6 on 2024-06-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RANK', models.IntegerField(default=0)),
                ('NAME', models.CharField(max_length=100)),
                ('LANGUAGE', models.CharField(max_length=100)),
                ('TYPE', models.CharField(max_length=100)),
                ('MOST_STREAMED_GAME', models.CharField(max_length=100)),
                ('AVERAGE_STREAM_DURATION', models.FloatField(default=0)),
                ('FOLLOWERS_GAINED_PER_STREAM', models.FloatField(default=0)),
                ('AVG_VIEWERS_PER_STREAM', models.FloatField(default=0)),
                ('AVG_GAMES_PER_STREAM', models.FloatField(default=0)),
                ('TOTAL_TIME_STREAMED', models.FloatField(default=0)),
                ('TOTAL_FOLLOWERS', models.IntegerField(default=0)),
                ('TOTAL_VIEWS', models.IntegerField(default=0)),
                ('TOTAL_GAMES_STREAMED', models.IntegerField(default=0)),
                ('ACTIVE_DAYS_PER_WEEK', models.FloatField(default=0)),
                ('MOST_ACTIVE_DAY', models.CharField(max_length=10)),
                ('DAY_WITH_MOST_FOLLOWERS_GAINED', models.CharField(max_length=10)),
            ],
        ),
    ]
