# Generated by Django 5.0.6 on 2024-06-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamers',
            name='ACTIVE_DAYS_PER_WEEK',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='AVERAGE_STREAM_DURATION',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='AVG_GAMES_PER_STREAM',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='AVG_VIEWERS_PER_STREAM',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='FOLLOWERS_GAINED_PER_STREAM',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='RANK',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='TOTAL_FOLLOWERS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='TOTAL_GAMES_STREAMED',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='TOTAL_TIME_STREAMED',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='streamers',
            name='TOTAL_VIEWS',
            field=models.IntegerField(),
        ),
    ]
