# Generated by Django 5.0.6 on 2024-06-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0002_alter_streamers_active_days_per_week_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streamers',
            new_name='Streamer',
        ),
    ]
