# Generated by Django 5.0.6 on 2024-06-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0003_rename_streamers_streamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='RANK',
        ),
    ]
