# Generated by Django 5.0.6 on 2024-06-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0004_remove_streamer_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='ACTIVE_DAYS_PER_WEEK',
            new_name='active_days_per_week',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='AVERAGE_STREAM_DURATION',
            new_name='average_stream_duration',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='AVG_GAMES_PER_STREAM',
            new_name='avg_games_per_stream',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='AVG_VIEWERS_PER_STREAM',
            new_name='avg_viewers_per_stream',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='DAY_WITH_MOST_FOLLOWERS_GAINED',
            new_name='day_with_most_followers_gained',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='FOLLOWERS_GAINED_PER_STREAM',
            new_name='followers_gained_per_stream',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='LANGUAGE',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='MOST_ACTIVE_DAY',
            new_name='most_active_day',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='MOST_STREAMED_GAME',
            new_name='most_streamed_game',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='TOTAL_FOLLOWERS',
            new_name='total_followers',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='TOTAL_GAMES_STREAMED',
            new_name='total_games_streamed',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='TOTAL_TIME_STREAMED',
            new_name='total_time_streamed',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='TOTAL_VIEWS',
            new_name='total_views',
        ),
        migrations.RenameField(
            model_name='streamer',
            old_name='TYPE',
            new_name='type',
        ),
    ]
